collections:
  - name: "sozluk"
    i18n:
      structure: single_file
      locales: [en, tr]
    label: "Sözlük"
    description: "Sözlük - kelime ekle"
    folder: "src/content/docs/" 
    create: true
    fields: 
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Explanation", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", required: false }
      - { label: "Turkish", name: "tr", widget: "text", required: false }
      - { label: "Azerbaijani", name: "az", widget: "text", required: false }
      - { label: "Turkmen", name: "tk", widget: "text", required: false }
      - { label: "Kyrgyz", name: "ky", widget: "text", required: false }
      - { label: "Kazakh", name: "kk", widget: "text", required: false }
      - { label: "Volga Tatar", name: "tt", widget: "text", required: false }
      - { label: "Crimean Tatar", name: "crh", widget: "text", required: false }
      - { label: "Uzbek", name: "uz", widget: "text", required: false }
      - { label: "Uyghur", name: "ug", widget: "text", required: false }
      - { label: "Sakha", name: "sah", widget: "text", required: false }
      - { label: "Göktürk", name: "otk", widget: "text", required: false }
      - { label: "Old Uighur", name: "oui", widget: "text", required: false }      
      - { label: "Tuvan", name: "tyv", widget: "text", required: false }
      - { label: "Chuvash", name: "cv", widget: "text", required: false }


backend:
  name: github
  repo: ulughann/tonga
  open_authoring: true
  auth_scope: repo

publish_mode: editorial_workflow
media_folder: "static/images/uploads" 
public_folder: "/images/uploads"

i18n:
  structure: multiple_folders
  locales: [en, tr]
  default_locale: en